### ISSUE TITLE
Swagger Supporting UI Files Not Loading

### ISSUE THREAD

**Issue by dwatson-seymour** [based-ghost/aspnet-core-vue-vuex-playground-template#1]
Hello,

When I cloned your project I found the UI never displayed in http://localhost:52530/docs/index.html?url=/docs/api-specification.json due to UseSpaStaticFiles. 

I found changing the Startup.cs to call UseSwaggerUi3 before UseSpaStaticFiles resolved the problem:

           app.UseStaticFiles();
            // Register the Swagger generator and the Swagger UI middlewares
            // NSwage.MsBuild + adding automation config in GhostUI.csproj makes this part of the build step (updates to API will be handled automatically)
            app.UseOpenApi();
            app.UseSwaggerUi3(settings =>
            {
                settings.Path = "/docs";
                settings.DocumentPath = "/docs/api-specification.json";
            });

            app.UseSpaStaticFiles();
            app.UseRouting();

Not sure if that's the best workaround, but it worked.

**Comment by based-ghost** [comment]
Thanks for the heads up - yea, ever since moving from .NET Core 2.x to .NET Core 3.x I've noticed intermittent failures with that. I think your solution may be the way to go though.

**Comment by based-ghost** [comment]
Fix suggested by @dwatson-seymour merged into Master
